# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm
    form: true
    mappings:
        document:
            uri_prefix: /documents
            upload_destination: '%kernel.project_dir%/public/documents'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        mapsicustomer_image:
            uri_prefix: /documents/images
            upload_destination: '%kernel.project_dir%/public/documents/images'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer